on:
  push:
    branches:
      - master

concurrency:
  group: docker
  cancel-in-progress: true

name: push-docker
jobs:
  publish:
    runs-on: ubuntu-latest
    if: "
      !endsWith(github.event.head_commit.message, '!minor')
      && !endsWith(github.event.head_commit.message, '!wip')
      && !endsWith(github.event.head_commit.message, '!WIP')
      && !startsWith(github.event.head_commit.message, 'doc:')
      && !startsWith(github.event.head_commit.message, 'test')
      "
    strategy:
      matrix:
        python-version: [ 3.9 ]
    steps:

      - uses: actions/checkout@master
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
          ref: ${{ github.head_ref }}

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - uses: actions/cache@v2
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ env.pythonLocation }}-${{ hashFiles('setup.cfg') }}

      - name: Set up Cloud SDK for GCR access
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.ORG_PROD_PROJECT}}
          service_account_key: ${{ secrets.ORG_CICD_GCP_CRED }}
          export_default_credentials: true

      - name: Use gcloud as a Docker credential helper
        run: |
          gcloud auth configure-docker
          docker build -t eu.gcr.io/${{ secrets.ORG_PROD_PROJECT }}/mail-watcher-example:latest -f Dockerfile .
          docker push eu.gcr.io/${{ secrets.ORG_PROD_PROJECT }}/mail-watcher-example:latest
